# Generated by Django 4.2.15 on 2024-08-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_remove_student_subjects_subject_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=10, unique=True)),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('middle_name', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('salary', models.FloatField(max_length=6)),
                ('date_hired', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
