# Generated by Django 4.2.15 on 2024-08-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0004_teacher_alter_subject_subject_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.TextField(max_length=20)),
                ('note', models.TextField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='middle_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.TextField(max_length=20),
        ),
    ]
