# Generated by Django 4.2.15 on 2024-08-27 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0005_position_alter_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id_no',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='reg.position'),
        ),
    ]
