# Generated by Django 4.2.15 on 2024-08-27 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0008_alter_teacher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.TextField(max_length=20),
        ),
    ]
